app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'ApplicationController@homeRedirect');
Route::get('/applications', 'ApplicationController@getUserApplications');

Route::get('/healthcheck',  'HealthCheckController@check');
Route::get('auth/login', 'Auth\AuthController@getLogin');
Route::post('auth/login', 'Auth\AuthController@postLogin');
Route::get('auth/logout', 'Auth\AuthController@getLogout');

// Registration routes...
Route::get('auth/register', 'Auth\AuthController@getRegister');
Route::post('auth/register', 'Auth\AuthController@postRegister');

// Password reset link request routes...
Route::get('password/email', 'Auth\PasswordController@getEmail');
Route::post('password/email', 'Auth\PasswordController@postEmail');
Route::get('password/update', 'ApplicationController@getUpdatePassword');
Route::post('password/update', 'ApplicationController@postUpdatePassword');

// Password reset routes...
Route::get('password/reset/{token}', 'Auth\PasswordController@getReset');
Route::post('password/reset', 'Auth\PasswordController@postReset');

/*Route::get('details', [
    'middleware' => 'auth',
    'uses' => 'Auth\AuthController@getUpdate'
]);
Route::post('details', [
    'middleware' => 'auth',
    'uses' => 'Auth\AuthController@postUpdate'
]);*/
Route::post('users/files', 'UserFileController@store');
Route::get('details', 'ApplicationController@getAccountUpdate');
Route::post('details', 'ApplicationController@postAccountUpdate');
Route::get('applications/create', 'ApplicationController@getApplication');
Route::get('redirect/app', 'ApplicationController@redirectToApplicationOrCreate');
Route::post('app', 'ApplicationController@postApplication');
Route::get('app/{id}', 'ApplicationController@getApplication');
Route::post('app/{id}', 'ApplicationController@postApplication');
Route::get('api/file/{file}', 'ApplicationController@getFileData');
Route::get('application/{id}', 'SubmissionController@previewSubmission');
Route::get('preview', 'SubmissionController@previewRedirect');
Route::get('emailpreview', 'SubmissionController@emailPreview');
Route::get('emailpreview/newuser', 'SubmissionController@emailPreviewNewUser');
Route::get('emailpreview/forgotpassword', 'SubmissionController@forgotPassword');
Route::get('emailpreview/defferedpayment', 'SubmissionController@emailPreviewDefferedPayment');
Route::get('emailpreview/submitted', 'SubmissionController@emailPreviewSubmitted');
Route::get('pay/{id}', 'SubmissionController@pay');
Route::get('judge/submit/{id}', 'SubmissionController@pay');
Route::get('submissions/add/{id}', 'SubmissionController@index');
Route::get('deferred', 'TransactionController@deferredConfirmation');
Route::get('submitted', 'SubmissionController@freeSubmitConfirmation');
Route::post('submissions/file', 'SubmissionController@file');
Route::get('submissions/{application}/files', 'SubmissionFileController@index');
Route::post('submissions/{application}/files', 'SubmissionFileController@store');
Route::post('submissions/{application}/files/duplicate', 'DuplicateWorkDetailsController@store');
Route::post('submissions/song', 'SubmissionController@song');
Route::post('submissions/emptysong', 'SubmissionController@emptySong');
Route::delete('submissions/{application}/songs/{song}', 'SubmissionSongController@destroy');
Route::get('submissions/remove/{id}', 'SubmissionController@remove');
Route::get('admin/submissions/remove/{id}', 'SubmissionController@remove')->name('admin_delete_application');
Route::get('admin/submissions/unremove/{id}', 'SubmissionController@unremove');
Route::get('media/stream/{sha1Name}/{name}', 'FileController@media');
Route::get('media/download/{sha1Name}/{name}', 'FileController@media');
Route::post('payment/postback', 'TransactionController@processPostBack');
Route::get('payment/postback', 'TransactionController@processGetBack');
Route::get('payment/confirmation', 'TransactionController@confirmation');
Route::get('admin/songs', 'AdminController@listSongs')->name('adminListSongs');
Route::get('admin/users', 'AdminController@listUsers')->name('adminListUsers');
Route::post('admin/remove/scores/from/round', 'AdminController@removeScoreFromRound');
Route::get('admin/applications', 'AdminController@listApplications')->name('adminListApplications');
Route::get('admin/preview/song/{id}', 'AdminController@previewSong')->name("previewSong");
Route::get('admin/change/app/state/{id}/{status}', 'AdminController@changeApplicationStatusTo')->name("changeAppStatus");
Route::get('admin/impersonate/account/{id}', 'AdminController@impersonateUser');
Route::get('admin/stop/impersonating', 'GeneralController@exitImpersonatingUser');
Route::post('admin/songs/to/round', 'AdminController@assignUsersToRound');
Route::get('admin/shortlist/song/to/round', 'AdminController@shortlistSongToRound')->name('shortListSongToRound');
Route::post('admin/delete/all/assignments', 'AdminController@deleteAllSongRoundsForJudgeByRound')->name('deleteAllSongRoundsForJudgeByRound');
Route::post('admin/remove/songs/to/round', 'AdminController@deleteUsersToRound');
Route::post('admin/score', 'AdminController@assignScoreToSong');
Route::post('admin/markasread', 'AdminController@markAsRead');
Route::get('admin/user/{id}', 'AdminController@getManageUser');
Route::post('admin/user/{id}', 'AdminController@postManageUser');
Route::get('admin/user', 'AdminController@getManageUser');
Route::post('admin/user', 'AdminController@postManageUser');
Route::get('admin/dashboard', 'AdminController@dashboard');
Route::get('admin/panels', 'AdminController@getPanels');
Route::post('transcoding/media', 'TranscodingController@update');
Route::any('api/v1/transcode/create', 'TranscodingController@receiveMockNewFilePost');
Route::get('admin/panel/{id}', 'AdminController@getManagePanel');
Route::post('admin/panel/{id}', 'AdminController@postManagePanel');
Route::get('admin/panel', 'AdminController@getManagePanel');
Route::post('admin/panel', 'AdminController@postManagePanel');
Route::get('admin/view/scores/{id}/{roundId}', 'AdminController@viewScores')->name('adminViewScores');
Route::get('admin/export/scores', 'AdminController@exportScoresToExcel')->name('adminExportScores');

app/User.php
<?php

namespace App;

use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Foundation\Auth\Access\Authorizable;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;

class User extends Model implements
    AuthenticatableContract,
                                    AuthorizableContract,
                                    CanResetPasswordContract
{
    use Authenticatable, Authorizable, CanResetPassword;
    const USER_ROLE_ADMIN = 'admin';
    const USER_ROLE_JUDGE = 'judge';
    const USER_ROLE_USER = 'user';

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'users';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['firstname', 'surname', 'email', 'address', 'address2', 'city', 'state', 'postcode', 'phone', 'confirm_terms', 'password', 'gender', 'additional_composers', 'bio'];
    protected $required = ['firstname', 'surname', 'email', 'address', 'city', 'state', 'postcode', 'phone'];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = ['password', 'remember_token'];

    /**
     * Get files owned by user
     */

    public function files()
    {
        return $this->hasMany('App\File');
    }

    public function scores()
    {
        return $this->hasMany('App\Score');
    }

    public function transactions()
    {
        return $this->hasMany('App\Transaction');
    }

    /**
     * Get applications owned by user
     */
    public function applications()
    {
        return $this->hasMany('App\Application');
    }

    public function panels()
    {
        return $this->belongsToMany('App\Panel', 'panel_users', 'user_id', 'panel_id');
    }

    public function country()
    {
        return $this->belongsTo('App\Country');
    }
    public function isValid()
    {
        if (\Config('app.profileHasBio')) {
            $this->required[] = 'bio';
        }
        if (\Config('app.profileHasProfileImage')) {
            $this->required[] = 'profile_image_file_id';
        }
        if (\Config('app.profileHasGender')) {
            $this->required[] = 'gender';
        }
        foreach ($this->required as $fill) {
            if (empty($this->$fill)) {
                return false;
            }
        }

        return true;
    }
    public function songRounds()
    {
        return $this->hasMany('App\SongRound', 'judge_id', 'id');
    }
    /**
     * Get profile image
     */
    public function profileImage()
    {
        return $this->belongsTo('App\File', 'profile_image_file_id');
    }
    public function getProfileImageUrlAttribute()
    {
        if (! $this->profileImage) {
            return;
        }

        return url("/app/users/{$this->id}/{$this->profileImage->name}");
    }
    public function getFullNameAttribute()
    {
        return $this->firstname . ' ' . $this->surname;
    }
    public function getDisplayNameAttribute()
    {
        return $this->getFullNameAttribute();
    }
    public function getUuidAttribute()
    {
        return 'user-'.$this->id;
    }
}

resources/views/submission/help.blade.php
<div>
    <span class="glyphicon glyphicon-upload" aria-hidden="true"></span>
    <h2><em>drag and drop</em> or <em>click to select</em> mp3 or m4a.</h2>
</div>

resources/views/submission/preview.blade.php
@extends(\App\Helpers\General::templateWithPrefix('layouts.home'))

@section('content')
    <div class="col-sm-12">
        @if(in_array(\Auth::user()->role, [\App\User::USER_ROLE_ADMIN]))
        <div class="panel panel-primary no-margin">
            <div class="panel-heading">
                <h3 class="panel-title">State</h3>
            </div>
            <div class="panel-body" id="submissions">
                <table class="table table-hover previewApplication">
                    <tbody>
                    <tr>
                        <th class="">Id</th>
                        <td>{{\Config('app.applicationPrefix')}}-{{ $application->id }}</td>
                    </tr>
                    <tr>
                        <th class="">Status</th>
                        <td>{{ $application->formattedStatus }}</td>
                    </tr>

                    <tr>
                        <th class="">{{ ucfirst(str_plural(\Config('app.filesName'))) }}</th>
                        <td>
                            {{ \App\Helpers\General::filteredSongsCount($application->songs) }}
                        </td>
                    </tr>
                    @if(\Config('app.canMakePayments'))
                    <tr>
                        <th class="">Paid</th>
                        <td class="">@if($application->totalPaid > 0)
                                ${{ $application->totalPaid }}
                            @else
                                -
                            @endif</td>
                    </tr>
                    @endif

                    @if(in_array(\Auth::user()->role, [\App\User::USER_ROLE_ADMIN]) and $application and $application->user)
                        <tr>
                            <th class="">Impersonate</th>
                            <td class=""><a href="/admin/impersonate/account/{{ $application->user->id }}">{{ $application->user->firstname }} {{ $application->user->surname }}</a></td>
                        </tr>
                    @endif

                    </tbody>
                </table>
            </div>
            <div class="panel-footer"></div>
        </div>
        @if(\Config('app.canMakePayments'))
        <div class="panel panel-primary no-margin">
            <div class="panel-heading">
                <h3 class="panel-title">Payments</h3>
            </div>
            <div class="panel-body">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th class="tLeft" style="width:1%">ID</th>
                        <th class="tCenter" style="width:15%">Settlement Date</th>
                        <th class="tCenter" style="width: 20%">Status</th>
                        <th class="tCenter">Expiry</th>
                        <th class="tCenter">Reference</th>
                        <th class="tCenter">Created</th>
                        <th class="tRight" style="width:1%">Amount</th>
                    </tr>
                    </thead>
                    <tbody>
                    @forelse ($application->transactions as $transaction)
                        <tr>
                            <td class="rLeft">{{ $transaction->txnid }}</td>
                            <td class="tCenter">{{ $transaction->settlement_date }}</td>
                            <td class="tCenter">{{ $transaction->rescode }} - {{ $transaction->restext }}</td>
                            <td class="tCenter">{{ $transaction->expiry }}</td>
                            <td class="tCenter">{{ $transaction->reference }}</td>
                            <td class="tCenter">{{ date_create($transaction->created_at) ? date_create($transaction->created_at)->format('d/m/Y H:i:s') : '' }}</td>
                            <td class="tRight">${{ number_format($transaction->amount/100, 2) }}</td>
                        </tr>
                    @empty
                        <tr>
                        <td colspan="8" style="text-align: center">
                            <div class="emptyTable">
                                <span class="glyphicon glyphicon-file" aria-hidden="true"></span>
                                <p>no transactions</p>
                            </div>
                        </td>
                        </tr>
                    @endforelse
                    </tbody>
                </table>
            </div>
            <div class="panel-footer"></div>
        </div>
        @endif
        @endif
        <div class="panel panel-primary no-margin">
            <div class="panel-heading">
                <h3 class="panel-title">Personal Details @if(!in_array(\Auth::user()->role, [\App\User::USER_ROLE_ADMIN]))<a href="/details" class="inline-edit">Edit</a>@endif</h3>
            </div>
            <div class="panel-body" id="submissions">
                <table class="table table-hover previewApplication">
                    <tbody>
                    <tr>
                    <th class="">Name</th>
                    <td class="">{{ $user->firstname }}</td>
                    </tr>

                    <tr>
                    <th class="">Surname</th>
                    <td class="">{{ $user->surname }}</td>
                    </tr>

                    <tr>
                    <th class="">Email</th>
                    <td class=""><a href="mailto:{{ $user->email }}">{{ $user->email }}</a></td>
                    </tr>

                    <tr>
                    <th class="">Phone</th>
                    <td class="">{{ $user->phone }}</td>
                    </tr>

                    @if(\Config('app.userHasDob'))
                    <tr>
                    <th class="">DOB</th>
                    <td class="">{{ (!empty($user->dob) and $user->dob != '0000-00-00 00:00:00' and date_create($user->dob)) ? date_create($user->dob)->format('d/m/Y') : '' }}</td>
                    </tr>
                    @endif

                    <tr>
                    <th class="">Address</th>
                    <td class="">{{ $user->address}}<br>{{$user->address2}}<br>{{$user->city}}, {{$user->state}}, {{$user->postcode}}, {{$user->country->name or ''}}</td>
                    </tr>

                    @if(!is_null($user->an_apra_member))
                    <tr>
                    <th class="">APRA Member</th>
                    <td class="">{{ $user->an_apra_member ? "Yes" : "No" }}</td>
                    </tr>
                    @endif

                    @if(!is_null($user->additional_composers))
                    <tr>
                    <th class="">Additional Composers</th>
                    <td class="">{{ $user->additional_composers }}</td>
                    </tr>
                    @endif
                    @if(!is_null($user->gender))
                    <tr>
                        <th class="">Gender</th>
                        <td class="">{{ ucfirst(trans($user->gender)) }}</td>
                    </tr>
                    @endif

                    @if(!empty($user->bio))
                    <tr>
                        <td colspan="2"><pre class="breakWords" style=""> {{ $user->bio }}</pre></td>
                    </tr>
                    @endif

                    @if($user->profileImage)
                        <tr>
                            <th class="">Profile Image</th>
                            <td class="previewThumb">
                                <img src="{{ $user->profile_image_url }}" class="thumbnail" alt="Profile Image" style="width: 300px;">
                                {{ $user->profileImage->name }}
                            </td>
                        </tr>
                    @endif

                    </tbody>
                </table>
            </div>
            <div class="panel-footer"></div>
        </div>
    </div>
    @if(!\Config('app.skipApplicationPage'))
    <div class="col-sm-12">
        <div class="panel panel-primary no-margin">
            <div class="panel-heading">
                <h3 class="panel-title">Application Details @if(!in_array(\Auth::user()->role, [\App\User::USER_ROLE_ADMIN]))<a href="/app/{{$application->id}}" class="inline-edit">Edit</a>@endif</h3>
            </div>
            <div class="panel-body" id="submissions">
                <table class="table table-hover previewApplication">
                    <tbody>

                    <tr>
                    <th class="">Gender</th>
                    <td class="">{{ ucfirst(trans($application->gender)) }}</td>
                    </tr>

                    <tr>
                    <th class="">On Behalf Of The Artist</th>
                    <td class="">{{ $application->on_behalf ? "Yes" : "No" }}</td>
                    </tr>

                    <tr>
                    <th class="">Performing Name</th>
                    <td class="">{{ $application->performing_name}}</td>
                    </tr>

                    <tr>
                    <th class="">Performing Right Association</th>
                    <td class="">{{ $application->performing_rights_association}}</td>
                    </tr>




                    @if($application->profileImage)
                        <tr>
                            <th class="">Profile Image</th>
                            <td class="previewThumb">
                                <img src="{{ $user->profile_image_url }}" class="thumbnail" alt="Profile Image" style="width: 300px;">
                                {{ $application->profileImage->name }}
                            </td>
                        </tr>
                    @endif
                    @if($application->parentAuth)
                        <tr>
                            <th class="">Parental Authorisation</th>
                            <td class="previewThumb" style="text-align: center">
                                <a class="thumbnail" href="/media/download/{{ $application->parentAuth->name_sha1 }}/{{ urlencode($application->parentAuth->name) }}">
                                    <img src="/media/download/{{ $application->parentAuth->name_sha1 }}/{{ urlencode($application->parentAuth->name) }}" /> {{ $application->parentAuth->name }}
                                </a>
                            </td>
                        </tr>
                    @endif

                    <tr>
                        <td colspan="2"><pre class="breakWords" style=""> {{ $application->bio }}</pre></td>
                    </tr>

                    </tbody>
                </table>

            </div>
            <div class="panel-footer"></div>
        </div>
    </div>
    @endif
    @foreach ($songs as $song)
        @if(!$song->parent)
        @include('submission/previewSong', ['song'=>$song])
        @endif
        @if($song->children)
            @foreach($song->children()->orderBy('title')->get() as $childSong)
                @include('submission/previewSong', ['song'=>$childSong])
            @endforeach
        @endif
    @endforeach
    @if(\Auth::user()->id == $user->id)

    <div class="col-sm-12">
        <div class="panel panel-primary no-margin actionContainer">
            <div class="panel-body  bottom">

            @if(\Config('app.canMakePayments'))

                @if(in_array($application->status, [\App\Application::STATE_UNPAID, \App\Application::STATE_DEFERRED]))
                    <a href="/pay/{{$application->id}}" class="mlm btn btn-lg btn-primary pull-right">Submit and Pay</a>
                    @else
                    <button class="btn btn-lg btn-primary mlm pull-right" disabled>Submit and Pay</button>
                @endif
                @if(in_array($application->status, [\App\Application::STATE_SONGS_PAID, \App\Application::STATE_DEFERRED]))
                    <a href="#" class="btn btn-lg btn-primary pull-right mlm" disabled>Submit and Pay Later</a>
                @else
                    <a href="/pay/{{$application->id}}?defer=true" class="btn btn-lg btn-primary pull-right mlm">Submit and Pay Later</a>
                @endif

            @else
                @if(in_array($application->status, [\App\Application::STATE_SUBMITTED]))
                    <button class="btn btn-lg btn-primary pull-right mlm" type="button" disabled>Submit For Judging</button>
                @else
                    <a href="/judge/submit/{{$application->id}}?submit=true"
                            id="submit-application"
                            class="btn btn-lg btn-primary pull-right"
                            type="button"
                            {{ ! $application->canBeSubmitted() ? 'disabled' : '' }}
                    >Submit For Judging</a>
                    <a href="/submissions/add/{{ $application->id }}"
                       class="btn btn-lg btn-default pull-right"
                       style="margin-right: 0.5em;"
                    >Back to application</a>
                @endif

            @endif

            </div>
        </div>
    </div>
    @else
        <div class="col-sm-12">
            <div class="panel panel-primary no-margin actionContainer">
                <div class="panel-body  bottom">
            </div>
            </div>
        </div>
    @endif
@endsection

resources/views/submission/submitted.blade.php
@extends(\App\Helpers\General::templateWithPrefix('layouts.home'))
@section('content')
    <div class="col-sm-12">
        <div class="panel panel-primary no-margin large-panel">
            <div class="panel-heading">
                <h3 class="panel-title">Confirmation</h3>
            </div>
            <div class="panel-body">
                <p>Thank you {{ $user->firstname or '' }} for submitting your application. </p>
                <p>You can update the details of your account, but you will need to create a new application if you wish to submit additional works. </p>
            </div>
        </div>
    </div>
@endsection