app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'ApplicationController@homeRedirect');
Route::get('/applications', 'ApplicationController@getUserApplications');

Route::get('/healthcheck',  'HealthCheckController@check');
Route::get('auth/login', 'Auth\AuthController@getLogin');
Route::post('auth/login', 'Auth\AuthController@postLogin');
Route::get('auth/logout', 'Auth\AuthController@getLogout');

// Registration routes...
Route::get('auth/register', 'Auth\AuthController@getRegister');
Route::post('auth/register', 'Auth\AuthController@postRegister');

// Password reset link request routes...
Route::get('password/email', 'Auth\PasswordController@getEmail');
Route::post('password/email', 'Auth\PasswordController@postEmail');
Route::get('password/update', 'ApplicationController@getUpdatePassword');
Route::post('password/update', 'ApplicationController@postUpdatePassword');

// Password reset routes...
Route::get('password/reset/{token}', 'Auth\PasswordController@getReset');
Route::post('password/reset', 'Auth\PasswordController@postReset');

/*Route::get('details', [
    'middleware' => 'auth',
    'uses' => 'Auth\AuthController@getUpdate'
]);
Route::post('details', [
    'middleware' => 'auth',
    'uses' => 'Auth\AuthController@postUpdate'
]);*/
Route::post('users/files', 'UserFileController@store');
Route::get('details', 'ApplicationController@getAccountUpdate');
Route::post('details', 'ApplicationController@postAccountUpdate');
Route::get('applications/create', 'ApplicationController@getApplication');
Route::get('redirect/app', 'ApplicationController@redirectToApplicationOrCreate');
Route::post('app', 'ApplicationController@postApplication');
Route::get('app/{id}', 'ApplicationController@getApplication');
Route::post('app/{id}', 'ApplicationController@postApplication');
Route::get('api/file/{file}', 'ApplicationController@getFileData');
Route::get('application/{id}', 'SubmissionController@previewSubmission');
Route::get('preview', 'SubmissionController@previewRedirect');
Route::get('emailpreview', 'SubmissionController@emailPreview');
Route::get('emailpreview/newuser', 'SubmissionController@emailPreviewNewUser');
Route::get('emailpreview/forgotpassword', 'SubmissionController@forgotPassword');
Route::get('emailpreview/defferedpayment', 'SubmissionController@emailPreviewDefferedPayment');
Route::get('emailpreview/submitted', 'SubmissionController@emailPreviewSubmitted');
Route::get('pay/{id}', 'SubmissionController@pay');
Route::get('judge/submit/{id}', 'SubmissionController@pay');
Route::get('submissions/add/{id}', 'SubmissionController@index');
Route::get('deferred', 'TransactionController@deferredConfirmation');
Route::get('submitted', 'SubmissionController@freeSubmitConfirmation');
Route::post('submissions/file', 'SubmissionController@file');
Route::get('submissions/{application}/files', 'SubmissionFileController@index');
Route::post('submissions/{application}/files', 'SubmissionFileController@store');
Route::post('submissions/{application}/files/duplicate', 'DuplicateWorkDetailsController@store');
Route::post('submissions/song', 'SubmissionController@song');
Route::post('submissions/emptysong', 'SubmissionController@emptySong');
Route::delete('submissions/{application}/songs/{song}', 'SubmissionSongController@destroy');
Route::get('submissions/remove/{id}', 'SubmissionController@remove');
Route::get('admin/submissions/remove/{id}', 'SubmissionController@remove')->name('admin_delete_application');
Route::get('admin/submissions/unremove/{id}', 'SubmissionController@unremove');
Route::get('media/stream/{sha1Name}/{name}', 'FileController@media');
Route::get('media/download/{sha1Name}/{name}', 'FileController@media');
Route::post('payment/postback', 'TransactionController@processPostBack');
Route::get('payment/postback', 'TransactionController@processGetBack');
Route::get('payment/confirmation', 'TransactionController@confirmation');
Route::get('admin/songs', 'AdminController@listSongs')->name('adminListSongs');
Route::get('admin/users', 'AdminController@listUsers')->name('adminListUsers');
Route::post('admin/remove/scores/from/round', 'AdminController@removeScoreFromRound');
Route::get('admin/applications', 'AdminController@listApplications')->name('adminListApplications');
Route::get('admin/preview/song/{id}', 'AdminController@previewSong')->name("previewSong");
Route::get('admin/change/app/state/{id}/{status}', 'AdminController@changeApplicationStatusTo')->name("changeAppStatus");
Route::get('admin/impersonate/account/{id}', 'AdminController@impersonateUser');
Route::get('admin/stop/impersonating', 'GeneralController@exitImpersonatingUser');
Route::post('admin/songs/to/round', 'AdminController@assignUsersToRound');
Route::get('admin/shortlist/song/to/round', 'AdminController@shortlistSongToRound')->name('shortListSongToRound');
Route::post('admin/delete/all/assignments', 'AdminController@deleteAllSongRoundsForJudgeByRound')->name('deleteAllSongRoundsForJudgeByRound');
Route::post('admin/remove/songs/to/round', 'AdminController@deleteUsersToRound');
Route::post('admin/score', 'AdminController@assignScoreToSong');
Route::post('admin/markasread', 'AdminController@markAsRead');
Route::get('admin/user/{id}', 'AdminController@getManageUser');
Route::post('admin/user/{id}', 'AdminController@postManageUser');
Route::get('admin/user', 'AdminController@getManageUser');
Route::post('admin/user', 'AdminController@postManageUser');
Route::get('admin/dashboard', 'AdminController@dashboard');
Route::get('admin/panels', 'AdminController@getPanels');
Route::post('transcoding/media', 'TranscodingController@update');
Route::any('api/v1/transcode/create', 'TranscodingController@receiveMockNewFilePost');
Route::get('admin/panel/{id}', 'AdminController@getManagePanel');
Route::post('admin/panel/{id}', 'AdminController@postManagePanel');
Route::get('admin/panel', 'AdminController@getManagePanel');
Route::post('admin/panel', 'AdminController@postManagePanel');
Route::get('admin/view/scores/{id}/{roundId}', 'AdminController@viewScores')->name('adminViewScores');
Route::get('admin/export/scores', 'AdminController@exportScoresToExcel')->name('adminExportScores');

app/User.php
<?php

namespace App;

use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Foundation\Auth\Access\Authorizable;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;

class User extends Model implements
    AuthenticatableContract,
                                    AuthorizableContract,
                                    CanResetPasswordContract
{
    use Authenticatable, Authorizable, CanResetPassword;
    const USER_ROLE_ADMIN = 'admin';
    const USER_ROLE_JUDGE = 'judge';
    const USER_ROLE_USER = 'user';

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'users';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['firstname', 'surname', 'email', 'address', 'address2', 'city', 'state', 'postcode', 'phone', 'confirm_terms', 'password', 'gender', 'additional_composers', 'bio'];
    protected $required = ['firstname', 'surname', 'email', 'address', 'city', 'state', 'postcode', 'phone'];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = ['password', 'remember_token'];

    /**
     * Get files owned by user
     */

    public function files()
    {
        return $this->hasMany('App\File');
    }

    public function scores()
    {
        return $this->hasMany('App\Score');
    }

    public function transactions()
    {
        return $this->hasMany('App\Transaction');
    }

    /**
     * Get applications owned by user
     */
    public function applications()
    {
        return $this->hasMany('App\Application');
    }

    public function panels()
    {
        return $this->belongsToMany('App\Panel', 'panel_users', 'user_id', 'panel_id');
    }

    public function country()
    {
        return $this->belongsTo('App\Country');
    }
    public function isValid()
    {
        if (\Config('app.profileHasBio')) {
            $this->required[] = 'bio';
        }
        if (\Config('app.profileHasProfileImage')) {
            $this->required[] = 'profile_image_file_id';
        }
        if (\Config('app.profileHasGender')) {
            $this->required[] = 'gender';
        }
        foreach ($this->required as $fill) {
            if (empty($this->$fill)) {
                return false;
            }
        }

        return true;
    }
    public function songRounds()
    {
        return $this->hasMany('App\SongRound', 'judge_id', 'id');
    }
    /**
     * Get profile image
     */
    public function profileImage()
    {
        return $this->belongsTo('App\File', 'profile_image_file_id');
    }
    public function getProfileImageUrlAttribute()
    {
        if (! $this->profileImage) {
            return;
        }

        return url("/app/users/{$this->id}/{$this->profileImage->name}");
    }
    public function getFullNameAttribute()
    {
        return $this->firstname . ' ' . $this->surname;
    }
    public function getDisplayNameAttribute()
    {
        return $this->getFullNameAttribute();
    }
    public function getUuidAttribute()
    {
        return 'user-'.$this->id;
    }
}

resources/views/admin/applications.blade.php
@extends(\App\Helpers\General::templateWithPrefix('layouts.home'))
@section('content')
    <div class="col-sm-3">
        @include('admin/applicationsFilters')
    </div>
    <div class="col-sm-9">
        @include('admin/sharedSearch')
        <div class="panel panel-primary no-margin large-panel">
            <div class="panel-heading">
                <h3 class="panel-title">Applications</h3>
            </div>
            <div class="panel-body">
                @include('admin/applicationsTable')
            </div>
        </div>
        <div>
            {!! $applications->appends($filterArray)->render() !!}
        </div>
        <div class="paginationCount" style="text-align: center">{{ $applications->count() }} of {{ $applications->total() }} results.</div>
    </div>
@endsection

resources/views/admin/applicationsTable.blade.php
<!-- Table -->
<table class="table table-hover">
    <thead>
    <tr>
        <th>Application</th>
        <th style="text-align: center">{{ ucfirst(str_plural(\Config('app.filesName'))) }}</th>
        @if(\Config('app.canMakePayments'))
        <th style="text-align: center">Paid</th>
        @endif
        <th style="text-align: center">Status</th>
    </tr>
    </thead>
    <tbody>
    @forelse($applications as $app)
        <tr class="clickable-row" data-href="/application/{{$app->id}}">

            <td style="text-align: left">
                <p>@if(!empty($app->performing_name)) <a href="/application/{{$app->id}}">{{ str_limit($app->performing_name, $limit = 40, $end = '...') }}</a>@else <a href="/application/{{$app->id}}">{{\Config('app.applicationPrefix')}}-{{ $app->id }}</a> @endif</p>
                <p class="smallDescription">
                    {{ date_create($app->created_at)->format('d/m/Y') }}, {{\Config('app.applicationPrefix')}}-{{ $app->id }},
                    @if(in_array(\Auth::user()->role, [\App\User::USER_ROLE_ADMIN]) and $app and $app->user)Impersonate: <a href="/admin/impersonate/account/{{ $app->user->id }}">{{ $app->user->firstname }} {{ $app->user->surname }}</a>@endif,
                    @if(in_array(\Auth::user()->role, [\App\User::USER_ROLE_ADMIN]))Action @if(!$app->trashed())<a href="/admin/submissions/remove/{{ $app->id }}">Delete</a> @else <a href="/admin/submissions/unremove/{{ $app->id }}">Restore</a> @endif @endif
                    @if(in_array(\Auth::user()->role, [\App\User::USER_ROLE_ADMIN]))
                        Change To:
                        @if($app and !\Config('app.canMakePayments') and $app->status != \App\Application::STATE_SUBMITTED)
                            <a href="{{route('changeAppStatus', ['id'=>$app->id, 'status'=>\App\Application::STATE_SUBMITTED]) }}">Submitted</a>
                        @endif
                        @if($app and \Config('app.canMakePayments') and $app->status != \App\Application::STATE_SONGS_PAID)
                            <a href="{{route('changeAppStatus', ['id'=>$app->id, 'status'=>\App\Application::STATE_SONGS_PAID]) }}">Paid</a>
                        @endif
                        @if($app and \Config('app.canMakePayments') and $app->status != \App\Application::STATE_DEFERRED)
                            <a href="{{route('changeAppStatus', ['id'=>$app->id, 'status'=>\App\Application::STATE_DEFERRED]) }}">Deferred</a>
                        @endif
                        @if($app and $app->status != \App\Application::STATE_UNPAID)
                            <a href="{{route('changeAppStatus', ['id'=>$app->id, 'status'=>\App\Application::STATE_UNPAID]) }}">Started</a>
                        @endif
                    @endif

                </p>
            </td>
            <td style="text-align: center">
                @if(isset($filterArray['filter']) and $filterArray['filter'] == \App\Http\Controllers\AdminController::FILTER_ARCHIVED )
                    {{ \App\Helpers\General::filteredSongsCount($app->songs()->onlyTrashed()->get()) }}
                @else
                    {{ \App\Helpers\General::filteredSongsCount($app->songs) }}
                @endif
            </td>
            @if(\Config('app.canMakePayments'))
                <td style="text-align:center;">
                    @if($app->totalPaid > 0)
                        ${{ $app->totalPaid }}
                    @else
                        -
                    @endif
                </td>
            @endif
            <td style="text-align: center">{{ $app->formattedStatus }}</td>
        </tr>
    @empty
        <tr>
            <td colspan="5">
                <div class="emptyTable">
                    <span class="glyphicon glyphicon-file" aria-hidden="true"></span>
                    <p>no applications</p>
                </div>
            </td>
        </tr>
    @endforelse
    </tbody>
</table>

resources/views/admin/assignedTable.blade.php
@if(isset($justAssigned))
<table class="table table-hover">
    <thead>
    <tr>
        <th width="50%" style="text-align: right;font-weight:bold;">Judge</th>
        <th width="" style="text-align: left;font-weight:bold;">Assigned</th>
    </tr>
    </thead>
    <tbody>
    @foreach($justAssigned['counts'] as $key => $assignmentCount)
            <tr>
                <td style="text-align: right">{{ $justAssigned['panel']->users->get($key)->fullName or '' }}</td>
                <td style="text-align: left">{{$assignmentCount}}</td>
            </tr>
    @endforeach
    </tbody>
</table>
@endif

resources/views/admin/dashboard.blade.php
@extends(\App\Helpers\General::templateWithPrefix('layouts.home'))
@section('content')
    <div class="col-md-12">
        <div class="panel panel-primary no-margin large-panel">
            <div class="panel-heading">
                <h3 class="panel-title">Dashboard</h3>
            </div>
            <div class="panel-body" id="updateDetails">
                <table class="table appTable table-hover">
                    <thead>
                    <tr>
                        <th></th>
                        <th>Today</th>
                        <th>This Week</th>
                        <th>Total</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <th><a href="/admin/applications">Applications</a></th>
                        <td>{{ $stats['applications']['today'] }}</td>
                        <td>{{ $stats['applications']['week'] }}</td>
                        <td>{{ $stats['applications']['total'] }}</td>
                    </tr>
                    <tr>
                        <th><a href="/admin/users">Users</a></th>
                        <td>{{ $stats['users']['today'] }}</td>
                        <td>{{ $stats['users']['week'] }}</td>
                        <td>{{ $stats['users']['total'] }}</td>
                    </tr>
                    <tr>
                        <th><a href="/admin/songs">All {{ ucfirst(\Config('app.filesNamePlural')) }}</a><br><sup>(by upload time)</sup> </th>
                        <td>{{ $stats['works']['today'] }}</td>
                        <td>{{ $stats['works']['week'] }}</td>
                        <td>{{ $stats['works']['total'] }}</td>
                    </tr>
                    </tr>
                    @if(\App\Helpers\General::stateIsAvailable(\App\Application::STATE_SUBMITTED))
                    <tr>
                        <th><a href="/admin/songs">Submitted {{ ucfirst(\Config('app.filesNamePlural')) }}</a></th>
                        <td>{{ $stats['worksSubmitted']['today'] }}</td>
                        <td>{{ $stats['worksSubmitted']['week'] }}</td>
                        <td>{{ $stats['worksSubmitted']['total'] }}</td>
                    </tr>
                    @endif

                    @if(\App\Helpers\General::stateIsAvailable(\App\Application::STATE_SONGS_PAID))
                    <tr>
                        <th><a href="/admin/songs">Paid {{ ucfirst(\Config('app.filesNamePlural')) }}</a></th>
                        <td>{{ $stats['worksPaid']['today'] }}</td>
                        <td>{{ $stats['worksPaid']['week'] }}</td>
                        <td>{{ $stats['worksPaid']['total'] }}</td>
                    </tr>
                    @endif

                    @if(\App\Helpers\General::stateIsAvailable(\App\Application::STATE_UNPAID))
                    <tr>
                        <th><a href="/admin/songs">Started {{ ucfirst(\Config('app.filesNamePlural')) }}</a></th>
                        <td>{{ $stats['worksStarted']['today'] }}</td>
                        <td>{{ $stats['worksStarted']['week'] }}</td>
                        <td>{{ $stats['worksStarted']['total'] }}</td>
                    </tr>
                    @endif

                    @if(\App\Helpers\General::stateIsAvailable(\App\Application::STATE_DEFERRED))
                    <tr>
                        <th><a href="/admin/songs">Deferred {{ ucfirst(\Config('app.filesNamePlural')) }}</a></th>
                        <td>{{ $stats['worksDeferred']['today'] }}</td>
                        <td>{{ $stats['worksDeferred']['week'] }}</td>
                        <td>{{ $stats['worksDeferred']['total'] }}</td>
                    </tr>
                    @endif

                    </tbody>
                </table>


            </div>
        </div>
    </div>
@endsection

resources/views/admin/panels.blade.php
@extends(\App\Helpers\General::templateWithPrefix('layouts.home'))
@section('content')
    <div class="col-md-12">
        <div class="panel panel-primary no-margin large-panel">
            <div class="panel-heading">
                <h3 class="panel-title">Panels</h3>
            </div>
            <div class="panel-body" id="updateDetails">
                <table class="table appTable table-hover">
                    <thead>
                    <tr>
                        <th style="text-align: left">Name</th>
                        <th>Members</th>
                        <th>Created</th>
                    </tr>
                    </thead>
                    <tbody>
                    @forelse($panels as $panel)
                        <tr class="clickable-row" data-href="/admin/panel/{{$panel->id}}">
                            <td style="text-align: left">
                                <p>
                                    {{$panel->name}}
                                </p>
                            </td>
                            <td>{{ $panel->users->count() }}</td>
                            <td>{{ date_create($panel->created_at)->format('d/m/Y') }}</td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="4">
                                <div class="emptyTable">
                                    <span class="glyphicon glyphicon-file" aria-hidden="true"></span>
                                    <p>no panels</p>
                                </div>
                            </td>
                        </tr>
                    @endforelse
                    </tbody>
                </table>


            </div>
            <div class="panel-footer">
                <a class="btn btn-lg btn-primary pull-right" href="/admin/panel">New Panel</a>
                <div style="clear:both"></div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/scores.blade.php
@extends(\App\Helpers\General::templateWithPrefix('layouts.home'))
@section('content')
    <div class="col-md-3">
        @include('admin/scoresFilter')
    </div>
    <div class="col-md-9">
            <div class="panel panel-default panel-primary">
                <!-- Default panel contents -->
                <div class="panel-heading">{{ $judge->fullName }}</div>
                @include('admin/scoresTable')
            </div>
    </div>
@endsection

resources/views/admin/scoresTable.blade.php
<table class="table table-hover">
    <thead>
    <tr>
        <th>Track</th>
        <th style="">Application</th>
        <th style="text-align: center">Score</th>
        <th style="text-align: right">Action</th>
    </tr>
    </thead>
    <tbody>
    @forelse($scores as $score)
        <?php $song = $score->song->children()->count() > 0 ? $score->song->children()->orderBy('title')->first() : $score->song; ?>
        <tr>
            <td style="width: 35%">@if($song->parent()->count() > 0)<span class="label label-info">{{$song->category->multi_track_name or ''}}</span> @endif <a href="/admin/preview/song/{{$score->song->id}}">{{$song->title or ''}}</a> @if(isset($song->category->name))<br> <p class="smallDescription">{{ $song->category->name or '' }}</p> @endif</td>
            <td><p class="smallDescription"><a href="/application/{{ $song->application->id or ''}}">{{ Config('app.applicationPrefix')}}-{{ $song->application->id or ''}}</a> - {{ $song->application->user->fullName or '' }} </p></td>
            <td style="text-align: center">{{$score->score }}</td>
            <td style="text-align: right;width: 30%">
                    <a class="btn btn-default" href="{{ route('shortListSongToRound', ['round_id'=>$currentRound->id, 'song_id'=>$score->song->id, 'action'=>$score->song->isShortListed($currentRound->id) ? 'unshortlist': 'shortlist']) }}">
                        {{ $song->isShortListed($currentRound->id) ? 'Unshortlist': 'Shortlist' }}
                    </a>
                <form action="/admin/remove/scores/from/round" method="post" style="display: inline;">
                    <input type="hidden" name="score_id" value="{{ $score->id }}" />
                    {!! csrf_field() !!}
                    <button type="submit" class="btn btn-primary">Delete</button>
                </form>
            </td>
        </tr>
    @empty
        <tr>
            <td colspan="4">
                <div class="emptyTable">
                    <span class="glyphicon glyphicon-file" aria-hidden="true"></span>
                    <p>no scores</p>
                </div>
            </td>
        </tr>

    @endforelse
    </tbody>
</table>

resources/views/admin/song.blade.php
@extends(\App\Helpers\General::templateWithPrefix('layouts.home'))
@section('content')

@include('submission/previewSong', ['song'=>$song, 'judgingRounds'=>$judgingRounds, 'scoreRange'=>$scoreRange])

    @if($song->is_multi_track)
        @foreach($song->children()->orderBy('title')->get() as $cSong)
            @include('submission/previewSong', ['song'=>$cSong, 'judgingRounds'=>$judgingRounds, 'scoreRange'=>$scoreRange])
        @endforeach
    @endif
@endsection

resources/views/admin/songsPagination.blade.php
<div class="advancedPagination">


    {!! $songs->appends(
        array_merge(
            $filterArray,
            [
                'round' => request('round')
            ]
        )
    )->render() !!}

</div>
<div class="paginationCount" style="text-align: center;clear:both;">
    {{ $songs->total() }} results.
</div>

resources/views/admin/songsTable.blade.php
<!-- Table -->
<table class="table table-hover">
    <thead>
    <tr>
        <th width="6%" style="text-align: right"><input type="checkbox" name="selectAll" class="selectAll" /></th>
        <th width="48%">{{ ucfirst(\Config('app.filesName')) }}</th>
        @if(isset($hasScore) and $hasScore)<th style="text-align: center">Score</th>@endif
        <th width="6%" style="text-align: right">Date</th>
    </tr>
    </thead>
    <tbody>
    @forelse ($songs as $index => $song)

        <tr @if(isset($hasScore) and $hasScore and isset($songScores[$song->id])) class="info" @endif>
            <td width="6%" style="text-align: right">
                <input type="checkbox" name="songs[]" value="{{$song->id}}" />

            </td>
            <td width="48%" style="text-align: left">
                <p>
                    <a href="{{ route('previewSong', ['search'=>$savedSearch->id, 'id'=>$song->id]) }}" class="">
                        @if($song->is_multi_track)
                            <span class="label label-info">
                                {{$song->multi_track_name}}
                            </span>

                            {{$song->children->sortBy('title')->first()->title or ''}}
                        @else
                            {{ $song->title }}
                        @endif
                    </a>
                    <br>
                    @if(!in_array(\Auth::user()->role, [\App\User::USER_ROLE_ADMIN]))
                        <p class="smallDescription">
                            @if($song->category)
                                Category: {{$song->category->name or '' }}
                            @endif
                        </p>
                    @endif
                </p>
                @if(in_array(\Auth::user()->role, [\App\User::USER_ROLE_ADMIN]))
                    <p class="smallDescription">
                        {{ $song->created_at->format('d/m/Y') }}
                        @if($song->application)<a href="/application/{{ $song->application->id }}">{{\Config('app.applicationPrefix')}}-{{ $song->application->id }}</a>
                        &nbsp;
                        Impersonate:
                        @if($song->application and $song->application->user)<a href="/admin/impersonate/account/{{ $song->application->user->id }}">{{ $song->application->user->firstname }} {{ $song->application->user->surname }}</a>@endif

                        @if(!\Config('app.skipApplicationPage') and !empty($song->application->performing_name))&nbsp; Artist: {{ $song->application->performing_name }}@endif

                        @if($song->application)&nbsp; Status: {{$song->application->formattedStatus}} &nbsp; @endif

                        @if(in_array(\Auth::user()->role, [\App\User::USER_ROLE_ADMIN]) and isset($roundId) and is_numeric($roundId))
                            Action: <a href="{{ route('shortListSongToRound', ['round_id'=>$roundId, 'song_id'=>$song->id, 'action'=>$song->isShortListed($roundId) ? 'unshortlist': 'shortlist']) }}">
                                {{ $song->isShortListed($roundId) ? 'Unshortlist': 'Shortlist' }}
                            </a>
                        @endif

                        @if($song->category)
                            {{$song->category->name or '' }}
                        @endif

                        @endif
                    </p>
                @endif
            </td>
            @if(isset($hasScore) and $hasScore)
            <td style="text-align: center;width: 5%;">
                @if(isset($songScores[$song->id]))
                    @if($songScores[$song->id] == 0)
                        <span class="glyphicon glyphicon-eye-open" style="color:#337ab7"></span>
                        @else
                        <span class="badge" style="background-color: #337ab7">
                        {{ $songScores[$song->id] }}
                        </span>
                    @endif
                @endif
            </td>
            @endif
            <td style="text-align: right" width="6%">{{ $song->created_at->format('d/m/Y') }}</td>
        </tr>
        @empty
        <tr>
            <td colspan="4">
                <div class="emptyTable">
                    <span class="glyphicon glyphicon-music" aria-hidden="true"></span>
                    <p>no {{ Config('app.filesNamePlural') }}</p>
                </div>
            </td>
        </tr>
    @endforelse
    </tbody>
    <tfoot>
    <tr><td colspan="4" style="text-align: center;padding-bottom:30px">
            @if($rounds and $rounds->count() > 0 and in_array(\Auth::user()->role, [\App\User::USER_ROLE_ADMIN]))
                <div style="clear:both;text-align: center;display: block;margin-bottom:20px;" class="mbm checkbox randomAssign">
                    <label><input type="checkbox" name="is_random" value="1" /> Randomly assign the entire result set seperately between each member of a panel. </label>
                    <input type="hidden" value="{{$savedSearch->id}}" name="search" />
                </div>
                <div class="form-group roundAssignment" style="">
                    <select id="judge" name="judge" class="form-control">
                        <optgroup label="Panels">

                            @foreach($panels as $panel)
                                <option value="{{ $panel->uuid }}"@if ($panel->uuid == old('judge')) selected="selected"@endif>{{ $panel->name }}</option>
                            @endforeach

                        </optgroup>
                        <optgroup label="Judges">
                            @foreach($judges as $judge)
                                <option value="{{ $judge->uuid }}"@if ($judge->uuid == old('judge')) selected="selected"@endif>{{ $judge->firstname }} {{ $judge->surname }}</option>
                            @endforeach
                        </optgroup>
                        <optgroup label="Admins">
                            @foreach($admins as $admin)
                                <option value="{{ $admin->uuid }}"@if ($admin->uuid == old('judge')) selected="selected"@endif>{{ $admin->firstname }} {{ $admin->surname }}</option>
                            @endforeach
                        </optgroup>

                    </select>
                    <select id="round" name="round" class="form-control">
                        @foreach($rounds as $round)
                            <option value="{{ $round->id }}"@if ($round->id == old('judge')) selected="selected"@endif>{{ $round->name }}</option>
                        @endforeach
                    </select>
                    <a id="assignSongs" class="btn btn-primary">
                        Assign
                    </a>
                </div>
            @endif
        </td>
    </tr>
    </tfoot>
</table>